cheers/apps/bar/api/urls.py
from django.conf.urls import url
from django.urls import path, include
from rest_framework import routers

from cheers.apps.bar.api.views.bar import ViewAPIBar
from cheers.apps.bar.api.views.bar_category import ViewAPIBarCategory
from cheers.apps.bar.api.views.check_subscription_expiration import ViewAPIBarCheckSubscriptionExpire
from cheers.apps.bar.api.views.order import ViewAPIBarOrder
from cheers.apps.bar.api.views.payment import ViewAPIBarPayment
from cheers.apps.bar.api.views.plan import ViewAPIBarPlan
from cheers.apps.bar.api.views.product import ViewAPIBarProduct
from cheers.apps.bar.api.views.rating import ViewAPIBarProductRating
from cheers.apps.bar.api.views.stripe_card_list import ViewAPIBarStripeCardList
from cheers.apps.bar.api.views.unsubscribe import ViewAPIBarUnsubscribe
from cheers.apps.bar.api.views.unsubscribe_reason import ViewAPIBarUnsubscribeReason

router = routers.DefaultRouter()

# User's has signup (POST), detail (GET), update (PATCH, PUT) api's
router.register('products', ViewAPIBarProduct, base_name='products')
router.register('orders', ViewAPIBarOrder, base_name='orders')
router.register('', ViewAPIBar, base_name='bars')



urlpatterns = [


    # path('list/',
    #     ViewAPIBar.as_view(), name='lists'),

    path('category/',
        ViewAPIBarCategory.as_view(), name='category'),

    path('plans/',
        ViewAPIBarPlan.as_view(), name='plans'),

    path('payment/',
        ViewAPIBarPayment.as_view(), name='payment'),

    path('cards/',
        ViewAPIBarStripeCardList.as_view(), name='cards'),



    path('check-subscription-expiration/',
        ViewAPIBarCheckSubscriptionExpire.as_view(), name='check-subscription-expiration'),

    path('rating/',
        ViewAPIBarProductRating.as_view(), name='rating'),

    path('unsubscribe/',
        ViewAPIBarUnsubscribe.as_view(), name='unsubscribe'),

    path('reasons/',
        ViewAPIBarUnsubscribeReason.as_view(), name='reasons'),

    path('', include(router.urls)),

]

cheers/apps/bar/urls.py
"""
                        BAR URL'S
"""


from django.urls.conf import path
from django.urls.conf import re_path

from cheers.apps.bar.views.bar_add_new import ViewBarAdd
from cheers.apps.bar.views.bar_detail import ViewBarDetail
from cheers.apps.bar.views.bar_drinks import ViewBarDrinks
from cheers.apps.bar.views.bar_owner_add import ViewBarOwnerAdd
from cheers.apps.bar.views.bar_owners import ViewBarOwners
from cheers.apps.bar.views.bar_update import ViewBarUpdate
from cheers.apps.bar.views.drink_add import ViewBarAddDrink
from cheers.apps.bar.views.drink_detail import ViewBarDrinkDetail
from cheers.apps.bar.views.drink_update import ViewBarDrinkUpdate
from cheers.apps.bar.views.list import ViewBarList
from cheers.apps.bar.views.products import ViewBarProducts
from cheers.apps.bar.views.publish import ViewBarPublish

urlpatterns = [
    #Bar urls
    path('add-bar/', ViewBarAdd.as_view(), name="add-bar"),
    path('list/', ViewBarList.as_view(), name="list"),
    path('<int:pk>/detail/', ViewBarDetail.as_view(), name='detail'),
    path('<int:pk>/update/', ViewBarUpdate.as_view(), name='update'),
    path('<int:pk>/drinks/', ViewBarDrinks.as_view(), name='drinks'),
    path('owners/', ViewBarOwners.as_view(), name='owners'),
    path('add-bar-owner/', ViewBarOwnerAdd.as_view(), name='add-bar-owner'),
 

    #Drinks urls
    path('add-drink/', ViewBarAddDrink.as_view(), name='add-drink'),
    path('drinks/', ViewBarProducts.as_view(), name='products'),
    path('<int:pk>/drink-detail/', ViewBarDrinkDetail.as_view(), name='drink-detail'),
    path('<int:pk>/drink-update/', ViewBarDrinkUpdate.as_view(), name='drink-update'),
    path('<int:pk>/publish/', ViewBarPublish.as_view(), name='publish'),





]

cheers/apps/bar/models/bar.py
from django.contrib.gis.geos import Point
from django.contrib.postgres.fields import JSONField
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.gis.db.models import PointField
from cheers.apps.account.models import ModelAccountUser
from cheers.apps.bar.models import ModelBarCategory, ModelBarProduct
from cheers.apps.base.models import ModelBaseCountry


class ModelBar(models.Model):
    """
    Store the data of bar.
    """

    owner = models.ForeignKey(ModelAccountUser, related_name="bars",
                              on_delete=models.CASCADE, help_text="Owner of the bar.")

    country = models.ForeignKey(ModelBaseCountry, related_name="bars",
                                on_delete=models.SET_NULL, null=True, help_text="Country of the bar.")

    name = models.CharField(max_length=500, help_text="Name of the bar.")

    address = models.TextField()
    latitude = models.DecimalField(max_digits=30, decimal_places=15, help_text="Latitude of bar address")

    longitude = models.DecimalField(max_digits=30, decimal_places=15, help_text="Longitude of bar address")

    drinks = models.ManyToManyField(ModelBarProduct, blank=True, related_name="bars")

    location = PointField(null=True, blank=True, srid=4326)
    description = models.TextField(blank=True, null=True)
    phone = PhoneNumberField(blank=True)
    email = models.EmailField(null=True, blank=True)
    bar_category = models.ManyToManyField(ModelBarCategory, related_name="bars")
    bar_timings = JSONField(default=dict)
    publish = models.BooleanField(default=False, help_text="Show the bar on app according to publish status")
    logo = models.ImageField(upload_to="bar/",
                             null=True, blank=True,
                             help_text="Logo of the bar")

    bar_photography = models.ImageField(upload_to="bar/photography/",
                             null=True, blank=True,
                             help_text="Logo of the bar")

    # -------------------------------------------------------------------------
    # Meta
    # -------------------------------------------------------------------------
    class Meta:
        db_table = "bar"
        verbose_name = "Bar"
        verbose_name_plural = "Bars"

    # ---------------------------------------------------------------------------
    # __str__
    # ---------------------------------------------------------------------------
    def __str__(self):
        """
        Returns the string representation of the bar object.
        """

        return self.name

    def save(self, *args, **kwargs):
        # keep location point in sync with lat, long
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude), float(self.latitude))

        return super(ModelBar, self).save(*args, **kwargs)

    @property
    def logo_preview(self):
        return self.logo.url if self.logo else '/static/images/dummy-logo2.jpg'

    @property
    def bar_photography_preview(self):
        return self.bar_photography.url if self.bar_photography else '/static/images/bar.jpeg'

cheers/apps/bar/forms/bar.py
from django import forms
from django.forms import FileInput

from cheers.apps.account.models import ModelAccountUser
from cheers.apps.bar.models import ModelBar, ModelBarCategory
from cheers.apps.base.models import ModelBaseCountry


class FormBar(forms.ModelForm):
    """
    This form handle the bar data
    """

    name = forms.CharField(label="Name of your bar (displayed in the application)*", widget=forms.TextInput(attrs={'class': 'form-control required'}))

    country = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'custom-select'}),
                                     queryset=ModelBaseCountry.objects.all(), label="City where your bar is located*")

    bar_photography = forms.FileField(widget=FileInput(attrs={'class':"custom-file-input"}))

    address = forms.CharField(widget=forms.TextInput(attrs={'rows': 4, 'class': 'form-control'}),
                              label="Address of your bar (Make sure this is the right location checking on the map below)*")

    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 8, 'class': 'form-control', 'maxlength': '1000'}),
                                  required=False, label="Description (Not more than 1000 words)")

    owner = forms.ModelChoiceField(widget=forms.Select(attrs={'class': 'custom-select'}),
                                   queryset=ModelAccountUser.objects.filter(is_bar_owner=True))

    class Meta:
        model = ModelBar
        fields = ('owner', 'country', 'name', 'address', 'latitude', 'longitude',
                  'description', 'bar_category', 'logo',  'bar_photography', 'bar_timings')

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', '')
        super(FormBar, self).__init__(*args, **kwargs)

        self.fields['bar_category'].widget = forms.widgets.CheckboxSelectMultiple()
        self.fields['bar_category'].queryset = ModelBarCategory.objects.all()
        self.fields['bar_category'].help_text = ""
        self.fields['bar_category'].label = "Bar Category (can choose multiple choices):"

        if self.request.user.is_bar_owner:
            self.fields['owner'].initial = self.request.user

cheers/apps/bar/forms/bar_timing_new.py
from django import forms
from django.forms import inlineformset_factory

from cheers.apps.bar.models import ModelBarTiming, ModelBar


class FormBarTiming(forms.ModelForm):
    """
    This form handle the data of bar timings.
    """

    day = forms.CharField(widget=forms.Select(choices=ModelBarTiming.DAY_CHOICES, attrs={'class': 'form-control col-md-9'}))

    class Meta:

        model = ModelBarTiming
        fields = ('day', 'start_time', 'end_time', 'is_closed')


BarTimingFormSet = inlineformset_factory(ModelBar, ModelBarTiming, extra=1, exclude=())

cheers/apps/bar/api/views/bar.py
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import Point
from django.contrib.gis.measure import D
from django.db.models import Q
from rest_framework.authentication import TokenAuthentication, SessionAuthentication
from rest_framework.generics import ListAPIView, DestroyAPIView
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from cheers.apps.bar.api.serializers.bar import SerializerBar
from cheers.apps.bar.models import ModelBar


class ViewAPIBar(ModelViewSet):
    """
    This class handle the list of bars
    """
    serializer_class = SerializerBar
    model = ModelBar

    def get_serializer_context(self):

        lat = self.request.GET.get('user_lat')
        lng = self.request.GET.get('user_lng')

        context = super(ViewAPIBar, self).get_serializer_context()
        if lat and lng:
            context['user_lat'] = lat
            context['user_lng'] = lng

        return context

    def get_queryset(self):
        """
        Return the data according to filter or all bars.
        """

        filters = {}
        query = self.request.GET.get("q", '')
        country = self.request.GET.get("country_id")
        category = self.request.GET.get("category_id")
        lat = self.request.GET.get('user_lat')
        lng = self.request.GET.get('user_lng')

        radius = self.request.GET.get("radius")

        queryset = self.model.objects.all()

        if country:
            filters['country__id'] = country

        if category:
            filters['bar_category__id'] = category.lower()

        if radius and lat and lng:
            ref_location = Point(float(lng), float(lat))
            print(radius)
            filters['location__distance_lt'] = (ref_location, D(km=radius))

        if filters:
            queryset = queryset.filter(Q(name__icontains=query) | Q(address__icontains=query), **filters)
            if radius and lat and lng:
                queryset = queryset.annotate(distance=Distance("location", ref_location)) \
                    .order_by('distance')

        return queryset

cheers/apps/bar/api/views/bar_category.py
from rest_framework.authentication import TokenAuthentication
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated

from cheers.apps.bar.api.serializers.bar_category import SerializerBarCategory
from cheers.apps.bar.models import ModelBarCategory
from cheers.apps.base.api.serializers.country import SerializerBaseCountry
from cheers.apps.base.models import ModelBaseCountry


class ViewAPIBarCategory(ListAPIView):
    """
    This class handle the category of bar.
    """
    model = ModelBarCategory
    serializer_class = SerializerBarCategory
    queryset = model.objects.all()
    pagination_class = None

cheers/apps/bar/api/views/check_subscription_expiration.py
from datetime import datetime

from rest_framework.response import Response
from rest_framework.views import APIView


class ViewAPIBarCheckSubscriptionExpire(APIView):
    """
    This view check the user subscription expiration date.
    """

    def get(self, request, *args, **kwargs):
        """
        This method check the expiration date.
        """
        try:
            subscription = request.user.subscription
            if self.request.user.is_today_order_allowed:
                today_order = True
            else:
                today_order = False
            if datetime.now().date() > subscription.expiration.date():
                subscription.active = False
                subscription.save()
                return Response({'expiration': True, "plan_id": None, "cancellation": False, "today_order": False})
            return Response(
                {'expiration': False, "plan_id": subscription.plan.id, "cancellation": subscription.cancellation,
                 "today_order": today_order})
        except AttributeError:
            return Response({'expiration': True, "plan_id": None, "cancellation": False, "today_order": False})

cheers/apps/bar/api/views/order.py
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet

from cheers.apps.bar.api.serializers.order import SerializerBarOrder
from cheers.apps.bar.models import ModelBarOrder


class ViewAPIBarOrder(ModelViewSet):
    """
    This class is used for bar order
    """

    serializer_class = SerializerBarOrder
    model = ModelBarOrder

    def get_queryset(self):
        """
        Return the order by user and ordered by latest created date.
        """

        user = self.request.user
        return self.model.objects.filter(user=user).order_by("-created")

cheers/apps/bar/api/views/payment.py
from rest_framework import status
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
import stripe

from cheers.apps.account.models import ModelAccountUser
from cheers.apps.bar.api.serializers.payment import SerializerBarPayment
from cheers.apps.bar.models import ModelBarPlan
from cheers.settings import STRIPE_SECRET_KEY
import logging

logger = logging.getLogger(__name__)


class ViewAPIBarPayment(APIView):
    """
    This class is used for payment
    """

    serializer_class = SerializerBarPayment

    def post(self, request):
        """
        Send the data for payment and created the subscription for the user.
        """

        serializer = self.serializer_class(data=request.data, context={"request":self.request})
        serializer.is_valid(raise_exception=True)

        plan = ModelBarPlan.objects.get(id=serializer.data.get("plan"))

        stripe.api_key = STRIPE_SECRET_KEY
        token = serializer.data.get('stripe_token')
        is_saved = serializer.data.get('is_saved')
        card_token = serializer.data.get('card_token')
        try:
            if token:
                if is_saved:
                    source = stripe.Customer.create_source(request.user.stripe_customer['id'], source=token)
                else:
                    source = token
                charge = stripe.Charge.create(
                    amount=round(plan.price) * 100,  # convert cent to dollar
                    currency=plan.currency,
                    description=plan.title,
                    source=source,
                )
            else:
                source = card_token
                charge = stripe.Charge.create(
                    amount=round(plan.price) * 100,  # convert cent to dollar
                    currency=plan.currency,
                    description=plan.title,
                    source=source,
                    customer=request.user.stripe_customer['id'],
                )
        except Exception as e:
            logger.error('Error while accepting payment: %s', e.__str__())
            return Response({"error": "Some error occured in payment. Please try again"},
                            status=status.HTTP_400_BAD_REQUEST)


        if charge.get("status") == "succeeded":
            plan.subscribe(request.user, transaction_details=charge, language=request.META.get('HTTP_ACCEPT_LANGUAGE', ''))

        return Response(charge, status=status.HTTP_200_OK)

cheers/apps/bar/api/views/plan.py
from rest_framework.authentication import TokenAuthentication
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated

from cheers.apps.bar.api.serializers.plan import SerializerBarPlan
from cheers.apps.bar.models import ModelBarCategory, ModelBarPlan


class ViewAPIBarPlan(ListAPIView):
    """
    This class handle the Plan of bar.
    """
    model = ModelBarPlan
    serializer_class = SerializerBarPlan
    queryset = model.objects.filter(is_active=True, default=True)
    pagination_class = None

files/templates/bar/bar-drinks.html
{% extends 'base/form-base.html' %}
{% load staticfiles %}

{% block page-css %}
<link rel="stylesheet" href="{% static 'css/libs/wizard.css' %}"/>
<link rel="stylesheet" href="{% static 'css/bar/add-drink-to-bar.css' %}"/>
<link rel="stylesheet" href="{% static 'css/bar/wizard-add-drinks.css' %}"/>

<style>
    .bar_inner_logo, #preview {
    width: 55px;
}


</style>
{% endblock page-css %}
{% block header_title %}{{object.name}}{% endblock header_title %}

{% block content %}
<div class="row bar_inner">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <!--                 <a href="{% url 'bar:add-drink' %}?bar={{object.id}}" class="btn btn-lg btn-secondary pull-right">Add Drink</a>-->
                <h2 class="panel-title">Add Drinks to {{form.instance}}</h2>
            </header>
            <div class="panel-body">
                <div class="wizard-top-br">
                    <div class="row">
                        <div id="crumbs">
                            <ul>
                                <li><a href="#">1.Add a bar</a></li>
                                <li><a href="#" class="active">2.Add Drinks</a></li>
                                <li><a href="#">3.Publish on App</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                {% if form.errors %}
                <div class="text-danger text-left">
                    {% for error in form.errors %}
                    <strong>{{ error|escape }}</strong> <br>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="container add-drink1">
                    <div class="row justify-content-center">
                        <div class="col-xl-6 col-lg-10 col-md-12 col-sm-12 col-12">
                            <div class="wizard-logo">
                                <form method="post" enctype="multipart/form-data" class="drink-form">
                                    {% csrf_token %}
                                    <div class="slct-pic">
                                        <img src="{% static 'images/slct-img.png' %}" id="preview" alt="image"/>
                                    </div>
                                    <div class="form-group">
                                        <h4 class="wizard-h4">Upload your own drink picture, name and description :</h4>
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input" id="image" name="image"
                                                   aria-describedby="inputGroupFileAddon01">
                                            <label class="custom-file-label" for="image">Choose file</label>
                                        </div>
                                        <input type="text" class="form-control mt-4" placeholder="Name of the Drink"
                                               name="name">
                                        <textarea class="form-control mt-4" placeholder="Description of the Drink"
                                                  name="description"
                                                  rows="5"></textarea>
                                        <button type="submit" class="btn btn-primary form-control mt-4">ADD DRINK TO
                                            OFFER
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <hr>

                    <div class="row justify-content-center multiple-drinks">
                        <div class="col-xl-7 col-lg-10 col-md-12 col-sm-12 col-12">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="d-none">
                                    {{form.drinks}}
                                </div>
                                <h4 class="wizard-h4 text-center">Or Choose from a pre-selection below (can choose
                                    multiple drinks) :</h4>
                                <ul class="multiple-drinks d-flex flex-wrap mt-5">
                                    {% for drink in view.get_default_drinks %}
                                    <li>
                                        <label for="{{drink.id}}"><img src="{{drink.image.url}}" alt="image"/></label>
                                        <div class="custom-control custom-checkbox mt-5">
                                            <input type="checkbox" class="custom-control-input drink-select-checkbox"
                                                   id="{{drink.id}}" name="drink">
                                            <label class="custom-control-label"
                                                   for="{{drink.id}}">{{drink.name}}</label>
                                        </div>
                                    </li>
                                    {% endfor %}
                                    {% for drink in view.get_user_drinks %}
                                    <li>
                                        <label for="{{drink.id}}"><img src="{{drink.image.url}}" alt="image"/></label>
                                        <div class="custom-control custom-checkbox mt-5">
                                            <input type="checkbox" class="custom-control-input drink-select-checkbox" id="{{drink.id}}"
                                                   name="drink">
                                            <label class="custom-control-label"
                                                   for="{{drink.id}}">{{drink.name}}</label>
                                        </div>
                                    </li>
                                    {% endfor %}
                                </ul>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-lg-8 col-md-12 col-sm-12 drink-displayed mt-5" id="show-drinks">
                            <p class="mt-5">Drinks you would like to offer will be displayed here. Please validate
                                below.</p>
                            <ul class="multiple-drinks d-flex flex-wrap mt-5 col-12 justify-content-center">
                                <!--<li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/bottle-beer.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/red-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/tequila-short.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>
                                <li>
                                    <img src="{% static 'images/house-white-wine.png' %}" alt="image"/>
                                    <span>house White Wine</span>
                                </li>-->
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="form-group drink_btn">
                    <div class="col-md-6">
                        <a href="{% url 'bar:update' form.instance.id %}">
                            <button type="button" class="cancel mb-xs mt-xs mr-xs btn btn-danger"><< Go Back</button>
                        </a>
                        <button type="submit" class="cancel next-stp mb-xs mt-xs mr-xs btn btn-danger" id="addBar">
                            Validate >>
                        </button>
                    </div>
                </div>
                </form>
            </div>
        </section>
    </div>
</div>
{% endblock content %}

{% block page-js %}
<script src="{% static 'js/base/common.js' %}"></script>
<script src="{% static 'js/libs/jquery.blockUI.js' %}"></script>
<script src="{% static 'js/bar/add-drink.js' %}"></script>
<script>
    function getSelectedDrinks(){
        drink_ids = []
        $('.drink-select-checkbox:checked').each(function(index, el){
            drink_ids.push($(el).attr('id'));
        })
        return drink_ids;
    }

    function checkedDrinks(id, image_src, name){
        html =`<li data-id='`+id+`'>
                <label><img src='`+image_src+`' alt='image'></label>
                <div>
                    <label>`+name+`</label>
                </div>
            </li>`
        $("#show-drinks ul").append(html);
    }

    function removeElementByID(id){
        $("#show-drinks ul").find("li[data-id='" + id + "']").remove();
    }


    function processItem(item){

        var inputValue = $(item).attr("id");
        var image = $(item).closest('li').find("img").attr("src")
        var name = $(item).parent().find('label').text();
        if ($(item).prop('checked')){
            checkedDrinks(inputValue, image, name);
        } else {
            removeElementByID(inputValue);
        }
     }

     $( document ).ready(function() {
        $(document).on('change', '.drink-select-checkbox', function() {
            $('#id_drinks').val(getSelectedDrinks());
        });

        // mark the items selected which comes from backend in the multiselect hidden field #id_drinks
        var drinks = $('#id_drinks').val();
        $(drinks).each(function(index, id){
            $('[id=' + id + ']').attr('checked', true);
            // Show as chosen items
            processItem($("#"+id));
        });


        // On item select/unselect add/remove to chosen items respectively
        $('input[type="checkbox"]').click(function(){
            processItem($(this));
         });



            // Get list of checked values
        var selected = [];
<!--        $("input[name='drink']:checked").each(function() {-->
<!--            var selectedDrink = $(this).attr('id');-->
<!--            alert(selectedDrink);-->
<!--        });-->


    });




</script>
{% endblock page-js %}

files/templates/bar/drink-detail.html
{% extends 'base/form-base.html' %}
{% load staticfiles %}

{% block header_title %}{{object.name}}{% endblock header_title %}

{% block content %}
<div class="row bar_inner">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <h2 class="panel-title">Detail</h2>
            </header>
            <div class="panel-body">
                <div class="row edit_bar">
                    <div class="col-md-11">
                        <img class="bar_inner_logo" src="{{object.preview_image}}" alt="user">
                        <h6>{{object.name}}</h6>
                    </div>
                    <div class="col-md-1">
                        <a href="{% url 'bar:drink-update' object.id %}">
                            <button type="button" class="edit mb-xs mt-xs mr-xs btn btn-danger"><i
                                    class="fa fa-edit"></i>
                            </button>
                        </a>
                    </div>
                    <p>{{object.description}}</p>
                </div>
            </div>
        </section>
    </div>
</div>
{% endblock content %}